service:
  Name: account_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8080
  Mode: debug

grpc:
  Port: 50051
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5


logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  DNS_URL: "host=account_db port=5432 user=admin password=secret dbname=account_db sslmode=disable"

migration:
  Enable: true
  Recreate: false

jwtConfig:
  SecretKey: "804a3f9aa8ad199cb71ae7bacefd9357"
  AccessTokenExpire: 5 # in minutes
  RefreshTokenExpire: 15 # in minutes

