service:
  Name: order_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8082
  Mode: debug

grpc:
  Port: 50053
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  Host: localhost
  Port: 5434
  User: admin
  Password: secret
  Dbname: order_db
  SslMode: false

migration:
  Enable: true
  Recreate: false

rpcEndpoints:
  authSvc: "localhost:50051"
  productSvc: "localhost:50052"
