service:
  Name: purchase_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8080
  Mode: debug

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

rpcEndpoints:
  authSvc: "reverse-proxy:80"
  productSvc: "reverse-proxy:80"

kafka:
  Brokers: ["host.docker.internal:9091"]
