service:
    Name: account_service
    Mode: Development
    Debug: true
    ReadTimeout: 5
    WriteTimeout: 5

grpc:
  port: 50051

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  Host: localhost
  Port: 5432
  User: admin
  Password: secret
  Dbname: account_db
  SslMode: false

migration:
  enable: true
  recreate: false

