service:
  Name: product_service
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5

http:
  Port: 8081
  Mode: debug

grpc:
  Port: 50052
  Timeout: 15
  Time: 5
  MaxConnectionIdle: 30
  MaxConnectionAge: 5

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  DNS_URL: "host=localhost port=5433 user=admin password=secret dbname=product_db sslmode=disable"

migration:
  Enable: true
  Recreate: false

rpcEndpoints:
  authSvc: "localhost:50051"

kafka:
  Brokers: ["localhost:9091"]
